id = "apps"

[[commands]]
name = "apps"
exec = [
"""
brew install \
    iterm2 \
    maccy \
    macpass \
    numi \
    menumeters \
    rectangle \
    gpg-suite-no-mail \
    dteoh-devdocs \
    mouse-fix \
    shellcheck \
    secretive
""",
]

# background-music 
# sensiblesidebuttons
