id = "apps"

[[commands]]
exec = ["""
brew install \
    iterm2 \
    maccy \
    macpass \
    numi \
    menumeters \
    rectangle \
    mouse-fix \
    shellcheck
"""]

# dteoh-devdocs
# gpg-suite-no-mail
# background-music 
# sensiblesidebuttons
