[settings]
id = "fzf"

[[commands]]
os = ["darwin"]
exec = [
    "brew install fzf",
    "[ -f /usr/local/opt/fzf/install ]    && /usr/local/opt/fzf/install --no-update-rc;    exit 0",    # depending on the homebrew installation it's either one ...
    "[ -f /opt/homebrew/opt/fzf/install ] && /opt/homebrew/opt/fzf/install --no-update-rc; exit 0",    # ... or the other
]

# fzf script fails to update the correct .zshrc when run e.g. in a vs code terminal, e.g.
# "Update /var/folders/c2/c287hy7d1n17sjlxsn7ctph00000gn/T/vscode-zsh/.zshrc"
[[config]]
path = "~/.zshrc"
comment_symbol = "#"
append = """
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
"""
