[settings]
id = "git"

[[variables]]
input = [
	{ var = "SSH_PUB_KEY_PATH", prompt = "Path to your public SSH key as shown in Secretive" },
	{ var = "EMAIL", prompt = "Email to use for git commits (e.g. work or personal address)" },
]

[[config]]
path = "~/.gitconfig"
comment_symbol = "#"
append = """
[user]
	name = Simon Jürgensmeyer
	email = {{ .Var.EMAIL }}
	signingKey = {{ .Var.SSH_PUB_KEY_PATH }}
[commit]
	gpgSign = true
[merge]
	conflictstyle = diff3
[rerere]
	enabled = true
[rebase]
	autoStash = true
[pull]
	rebase = false
[init]
	defaultBranch = main
[gpg]
	format = ssh
[tag]
	gpgSign = true
"""

[[config]]
path = "~/.config/git/ignore"
comment_symbol = "#"
append = """
.DS_Store
.vscode/
"""
