id = "git"

[[variables]]
input = [
    ["SSH_PUB_KEY_PATH", "Path to your public SSH key as shown in Secretive"],
]

[[config]]
path = "~/.gitconfig"
comment_symbol = "#"
append = """
[user]
	name = Simon Jürgensmeyer
	email = simon.juergensmeyer@gmail.com
	signingKey = {{ .Var.SSH_PUB_KEY_PATH }}
[commit]
	gpgSign = true
[merge]
	conflictstyle = diff3
[rerere]
	enabled = true
[rebase]
	autoStash = true
[pull]
	rebase = false
[init]
	defaultBranch = main
[gpg]
	format = ssh
[tag]
	gpgSign = true
"""

[[config]]
path = "~/.config/git/ignore"
comment_symbol = "#"
append = """
.DS_Store
"""
