[settings]
id = "helix"

[[commands]]
exec = ["brew install helix"]

[[config]]
path = "~/.zshrc"
comment_symbol = "#"
append = """
export EDITOR=hx
export VISUAL=$EDITOR
"""

[[config]]
path = "~/.config/helix/config.toml"
comment_symbol = "#"
append = """
theme = "ayu_mirage"
"""
