[settings]
id = "macos"

# apps
[[commands]]
exec = [
    """
brew install \
    iterm2 \
    maccy \
    macpass \
    numi \
    menumeters \
    rectangle \
    mouse-fix \
    shellcheck \
    trex
""",
]
# dteoh-devdocs
# gpg-suite-no-mail
# background-music 
# sensiblesidebuttons


# settings
[[commands]]
exec = [
    "defaults write com.apple.Dock autohide-delay -float 0 && killall Dock", # (enable delay again: defaults delete com.apple.Dock autohide-delay && killall Dock)
    "echo 'password for pmset' && sudo pmset -a womp 0",                                                  # Disable wake-on-lan
]
