[settings]
id = "macos"
os = ["darwin"]

# apps
[[commands]]
exec = [
    """
brew install \
    iterm2 \
    maccy \
    macpass \
    iina \
    menumeters \
    rectangle \
    mouse-fix \
    shellcheck \
    trex
""",
]
# dteoh-devdocs
# gpg-suite-no-mail
# background-music 
# sensiblesidebuttons
# numi

# settings
[[commands]]
exec = [
    # (enable delay again: defaults delete com.apple.Dock autohide-delay && killall Dock)
    "defaults write com.apple.Dock autohide-delay -float 0 && killall Dock", 
]

[[config]]
path = "~/.zshrc"
comment_symbol = "#"
append = """
HOMEBREW_BUNDLE_FILE=~/Brewfile
"""

