[settings]
id = "podman"

[[commands]]
os = ["darwin"]
exec = [
    "brew install podman-desktop",
    "sudo podman-mac-helper install",
]


# Create adjusted default machine when desired, e.g.
#   podman machine rm
#   podman machine init --disk-size 30 --cpus 2 --memory 4096

# Adjust disk/cpu/memory (disk can only grow)
#   podman machine set --disk-size 30 --cpus 2 --memory 4096

[[config]]
path = "~/.zshrc"
comment_symbol = "#"
append = """
export KIND_EXPERIMENTAL_PROVIDER=podman
export DOCKER_HOST=unix:///{{.Env.HOME}}/.local/share/containers/podman/machine/podman.sock
"""

# As an alternative to an alias which also works in Makefiles etc.
# When I decide this is overkill and the red warning is not needed,
# create a symbolic link instead, e.g: ln -s /usr/local/bin/podman /usr/local/bin/docker
[[config]]
truncate = true
path = "~/.local/bin/docker"
perm_file = 0o744
comment_symbol = "#"
append = """
#!/usr/bin/env bash
set -euo pipefail

RED='\\033[0;31m'
NO_COLOR='\\033[0m'

echo -e "${RED}WARNING: using podman${NO_COLOR}" 
podman "$@"
"""

# Podman builds images with a "localhost/" prefix when no registry is given.
# Docker does not or handles it as it would have a "docker.io/" prefix.
# Thus, with podman you have to explicitly tag the images without a registry name with "docker.io/IMAGE_NAME"

# Alternative to
#   kind load docker-image IMAGE_NAME
#   -->
#   kind load image-archive <(podman save IMAGE_NAME)
