[settings]
id = "podman"

[[commands]]
exec = [
    "brew install podman-desktop",
]

# Create adjusted default machine when desired, e.g.
#   podman machine rm
#   podman machine init --disk-size 30 --cpus 2 --memory 4096

# Adjust disk/cpu/memory (disk can only grow)
#   podman machine set --disk-size 30 --cpus 2 --memory 4096

[[config]]
path = "~/.zshrc"
comment_symbol = "#"
append = """
export KIND_EXPERIMENTAL_PROVIDER=podman
"""

# As an alternative to an alias which also works in Makefiles etc.
# When I decide this is overkill and the red warning is not needed,
# create a symbolic link instead, e.g: ln -s /usr/local/bin/podman /usr/local/bin/docker
[[config]]
path = "~/bin/docker"
comment_symbol = "#"
append = """
#!/usr/bin/env bash
set -euo pipefail

RED='\\033[0;31m'
NO_COLOR='\\033[0m'

echo -e "${RED}WARNING: using podman${NO_COLOR}" 
podman "$@"
"""

[[commands]]
after_configs = true
exec = [
    "set -x; chmod +x ~/bin/docker",
]
