[settings]
id = "secretive"

[[commands]]
exec = ["brew install secretive"]

[[config]]
path = "~/.ssh/config"
comment_symbol = "#"
append = """
Host *
	IdentityAgent ~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
"""

[[config]]
path = "~/.zshrc"
comment_symbol = "#"
append = """
export SSH_AUTH_SOCK=$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
"""
