id = "secretive"

[[commands]]
name = "secretive"
exec = [
"""
brew install secretive
""",
]

# check path of user dir
[[config]]
path = "~/.ssh/config"
comment_symbol = "#"
append = """
Host *
	IdentityAgent /Users/simon/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
"""

# check path of user dir
[[config]]
path = "~/.zshrc"
comment_symbol = "#"
append = """
export SSH_AUTH_SOCK='/Users/simon/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh'
"""
