# ****************
# !Use secretive!
# ****************

#[[config]]
#path = "~/.ssh/config"
#comment_symbol = "#"
#append = """
#Host *
#   AddKeysToAgent yes
#   IgnoreUnknown UseKeychain
#   UseKeychain yes     
#"""
