[settings]
id = "starship"
deactivated = true

[[commands]]
os = ["darwin"]
exec = ["brew install starship"]

[[config]]
priority = 1100
path = "~/.zshrc"
comment_symbol = "#"
append = """
eval "$(starship init zsh)"
"""

[[config]]
path = "~/.config/starship.toml"
comment_symbol = "#"
append = """
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = \"""
$username\\
$hostname\\
$localip\\
$shlvl\\
$singularity\\
$kubernetes\\
$directory\\
$vcsh\\
$git_branch\\
$git_commit\\
$git_state\\
$git_metrics\\
$git_status\\
$hg_branch\\
$docker_context\\
$package\\
$sudo\\
$cmd_duration\\
$line_break\\
$jobs\\
$battery\\
$time\\
$status\\
$container\\
$shell\\
$character\"""

[time]
disabled = true
format ="[$time]($style) "
"""
