[settings]
id = "vscodium"

[[config]]
path = "~/Library/Application Support/VSCodium/User/settings.json"
comment_symbol = "//"
append = """
{
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "diffEditor.ignoreTrimWhitespace": false,
    "git.enableSmartCommit": true,
    "git.openRepositoryInParentFolders": "never",
    "git.autofetch": true,
    "git.confirmSync": false,
    // "go.goroot": "~/.gvm/gos/go1.21",
    "go.testExplorer.packageDisplayMode": "nested",
    "go.testTimeout": "1m",
    "go.testFlags": [
        "-count=1", // don't cache test results
        "-v",
        "-race"
    ],
    "go.toolsManagement.autoUpdate": true,
    "gopls": {
        // "formatting.local": "<ADJUST ME>"
    },
    "go.inlayHints.compositeLiteralFields": true,
    "go.inlayHints.parameterNames": true,
    "editor.inlayHints.padding": true,
    "editor.inlayHints.fontFamily": "courier new",
    "terminal.integrated.scrollback": 10000,
    "redhat.telemetry.enabled": false,
    "window.zoomLevel": 1,
    "workbench.colorCustomizations": {
        "editorError.foreground": "#ff000000", // disable red underline
        "editorError.background": "#ff0000a0", // enable red background
    },
    "workbench.startupEditor": "none"
}
"""
