[settings]
id = "zsh-syntax-highlighting"

[[commands]]
exec = [
    "brew install zsh-syntax-highlighting",
]

[[config]]
path = "~/.zshrc"
comment_symbol = "#"
append = """
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
"""
