id = "zshrc"

# oh-my-zsh
[[commands]]
exec = [
    "rm -rf ~/.oh-my-zsh", # make it idempotent
    'KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"',
]

# oh-my-zsh
[[config]]
path = "~/.zshrc"
comment_symbol = "#"
append = """
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh
"""


# zsh-syntax-highlighting
[[commands]]
exec = [
    "brew install zsh-syntax-highlighting",
]

# zsh-syntax-highlighting
[[config]]
path = "~/.zshrc"
comment_symbol = "#"
append = """
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
"""

[[config]]
path = "~/.zshrc"
comment_symbol = "#"
append = """
setopt EXTENDED_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_BEEP
setopt SHARE_HISTORY             # Share history between all sessions.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt BANG_HIST                 # Treat the '!' character specially during expansion.

# commands that start with a space are not saved in the history
HISTCONTROL=ignorespace

# GOBIN in .zshrc
export PATH=$PATH:/$HOME/go/bin

# Homebrew Binaries etc
export PATH=$HOME/bin:/usr/local/bin:/opt/homebrew/bin:$PATH

# add time
PROMPT='%{$fg[yellow]%} %D{%H:%M} '$PROMPT

# Reset prompt for updating the time
#TMOUT=60 # seconds of updating
#
#TRAPALRM() {
#    zle reset-prompt
#}
"""
