- name: git
  hosts: localhost
  connection: local
  vars_prompt:
    - name: "ssh_pub_key_path"
      prompt: "Path to your public SSH key as shown in Secretive"
      private: false
    - name: "email"
      prompt: "Email to use for git commits (e.g. work or personal address)"
      private: false
  tasks:
    - name: setup git
      ansible.builtin.blockinfile:
        path: ~/.gitconfig
        append_newline: true
        prepend_newline: true
        marker_begin: BEGIN {{ ansible_play_name }}
        marker_end: END {{ ansible_play_name }}
        block: |
          # Added some settings from https://blog.gitbutler.com/how-git-core-devs-configure-git/
          [user]
            name = Simon Jürgensmeyer
            email = {{ email }}
            signingKey = {{ ssh_pub_key_path }}
          [commit]
            gpgSign = true
            verbose = true
          [merge]
            conflictstyle = diff3
          [rerere]
            enabled = false
          [rebase]
            autoStash = true
            updateRefs = true
            autoSquash = true
          [pull]
            rebase = false
          [push]
            autoSetupRemote = true
            default = simple
          [init]
            defaultBranch = main
          [gpg]
            format = ssh
          [tag]
            gpgSign = true
            sort = version:refname
          [fetch]
            prune = true
            pruneTags = true
            all = true
          [column]
            ui = auto
          [branch]
            sort = -committerdate
          [diff]
            algorithm = histogram
            renames = true
          [help]
            autocorrect = prompt

          [url "ssh://git@github.com/"]
            insteadOf = https://github.com/
    - name: setup gitignore
      ansible.builtin.blockinfile:
        path: ~/.config/git/ignore
        append_newline: true
        prepend_newline: true
        marker_begin: BEGIN {{ ansible_play_name }}
        marker_end: END {{ ansible_play_name }}
        block: |
          .DS_Store
          .vscode/
