- name: secretive
  hosts: localhost
  connection: local
  tasks:
    - name: install secretive
      community.general.homebrew_cask:
        name: secretive
        state: present
    - name: setup secretive zsh
      ansible.builtin.blockinfile:
        path: ~/.zshrc
        append_newline: true
        prepend_newline: true
        marker_begin: BEGIN {{ ansible_play_name }}
        marker_end: END {{ ansible_play_name }}
        block: |
          export SSH_AUTH_SOCK=$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
    - name: setup secretive 
      ansible.builtin.blockinfile:
        path: ~/.ssh/config
        append_newline: true
        prepend_newline: true
        marker_begin: BEGIN {{ ansible_play_name }}
        marker_end: END {{ ansible_play_name }}
        block: |
          Host *
            IdentityAgent ~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
